import * as npm from '@root/package.json';

export const environment = {
  version: npm.version,
  production: true,
  trackEvents: true,
  pilot: true,
  pwa: true,
  tealium: false,
  menuTopDisables: {
    profile: true,
  },
  lowEnviroments: false,
  isLocal: false,
  analyticalDomain: 'https://mi.bancopopular.com.co',
  screenShotPWA: false,
  siteKeyRecaptcha: '6Le4brEUAAAAAIXZ7UHWXo9TlPe17s1RA2-tIwNV',
  url_redirect:
    'https://www.bancopopular.com.co/cuenta-de-ahorros/sso?channel=pb&dDL=',
  url_redirect_credit:
    'https://www.bancopopular.com.co/solicitud-tarjeta-de-credito-on-line/',
  url_redirect_cdt:
    'https://d3n126b3rriukp.cloudfront.net/apertura-cdt/auth?channel=pb&t=',
  url_redirect_tuplus: 'https://www.tuplus.com.co/',
  url_return_of_pse:
    'https://mi.bancopopular.com.co/pagos/ob-bancaria/pse/exitoso',
  api: {
    base: 'https://pb-api-popular.avaldigitallabs.com',
    services: {
      optionsModules: '/api/administration-api/get-frontend-permissions',
      products: '/api/products/all',
      pdetail: '/api/products/product',
      movements: '/api/movements/all',
      movementsFile: '/api/movements/file',
      freeDestination: '/api/free-destination-credits/all',
      detailFreeDestination: '/api/free-destination-credits/product',
      pfm: {
        products: '/api/pfm-api/products',
        moviments: '/api/pfm-api/movements',
        expenses: '/api/pfm-api/expenses',
        items: '/api/pfm-api/items',
        creditCards: '/api/pfm-api/credit-cards',
        recategorize: '/api/pfm-api/recategorize',
      },
      login: '/api/v3/enrollment',
      loginDirect: '/api/auth-service/v1/token/request',
      coexistence: '/api/auth-service/v1/ath/url-pb',
      logout: '/api/auth-service/v1/token',
      statements: '/api/statement/periods',
      blockprods: '/api/product-administration/lock-product',
      pdf: '/api/statement/file',
      affiliation_products: '/api/affiliation-products-v2/active-products',
      loans: '/api/loans/registered',
      payment: '/api/loans/payment',
      loansTwoFa: '/api/loans/two-factor-auth/transaction',
      close_security_session: '/api/cipher/close-session',
      symmetric_key: '/api/cipher/symmetric-key',
      otpService: '/api/otp/generate',
      advertising: '/api/advertising-api',
      customer: {
        getProfile: '/api/customer/profile',
        updateProfile: '/api/customer/profile/update',
        catalogs: '/api/customer/catalogs/all',
        getSecureData: '/api/customer/mdm',
        updateSecureData: '/api/customer/mdm/update/secure-data',
      },
      alerts: {
        search_v1: '/api/alert-management/search-user-alerts',
        create_v1: '/api/alert-management/create-user-alerts',
        create: '/api/alert-manager/products',
        groups: '/api/alert-manager/groups',
        target: '/api/alert-manager/target',
        user: '/api/alert-manager/user',
        groups_type: '/api/alert-manager/groups/type',
        inactive: '/api/alert-manager/inactive',
        transaction: '/api/alert-manager/transaction',
      },
      preferences: {
        save: '/api/customer/preferences/save',
        delete: '/api/customer/preferences/delete',
        all: '/api/customer/preferences/all',
      },
      categoriesTransfer: '/api/transfers/categories',
      banks: '/api/affiliation-products-v2/available-banks',
      paymentAvailableBanks: '/api/loans/available-banks',
      paymentbankLoans: '/api/loans/bank-loans',
      paymentBill: '/api/billers/payments',
      paymentBillPayment: '/api/billers/loan-payment',
      paymentBillDetail: '/api/billers/loan-detail',
      pendingTransfer: '/api/transfers/pending',
      historyTransfer: '/api/transfers-history',
      scheduled: {
        create: '/api/transfers-schedule',
        search: '/api/transfers-schedule/search',
        delete: '/api/transfers-schedule/delete',
      },
      scheduledTransfer: '/api/transfers-schedule/search',
      validate_security_session: '/api/cipher/validate-session',
      cipher_public_key: '/api/cipher/public-key',
      getLoginServerPublicKey: '/api/auth-service/v1/public-key',
      validatePing: '/api/auth-service/v1/ping',
      financial_op: {
        registered: '/api/loans/registered',
        delete: '/api/loans/delete',
      },
      bills: {
        addAgreement: '/api/billers/register',
        allRegistered: '/api/billers/registered',
        agreementsAvailables: '/api/agreements/available',
        delete: '/api/billers/delete',
        availableAgreementsForPaymentSchedule:
          '/api/billers/available-agreements',
      },
      pay_stack_information: '/api/pila/information',
      pockets: {
        home: '/api/pockets/all',
        createpockets: '/api/pockets/create',
        categories: '/api/pockets/categories',
        detail: '/api/pockets/pocket',
        move: '/api/pockets/transfer',
        delete: '/api/pockets/delete',
        update: '/api/pockets/update',
      },
      paymentTaxes: {
        cities: '/api/taxes/cities',
        taxes: '/api/agreements/taxes',
        amount: '/api/taxes/amount',
        payment: '/api/taxes/payment',
      },
      recurring: {
        create: '/api/recurring/create',
        delete: '/api/recurring/delete',
        update: '/api/recurring/update',
      },
      getEnrollmentServerPublicKey: '/api/auth-manager/public-key',
      twoFa: '/api/enrollment/two-factor-auth/transaction',
      transferTwoFa: '/api/transfers/two-factor-auth/transaction',
      otherProducts: '/api/products/other-entities/all',
      changePassword: '/api/auth-service/v1/password',
      notificationSms: '/api/notification/notify-secure-data',
      operatorsName: '/api/cell-phone-recharge/operators-name',
      cellPhoneRecharge: '/api/cell-phone-recharge',
      psePrivate: {
        banks: '/api/pse/private/banks',
        init: '/api/pse/private/init',
        status: '/api/pse/private/status',
      },
      favoriteTransfer: '/api/favorite-transfers/all',
      favoriteDelete: '/api/favorite-transfers/delete',
      otp: '/api/otp/two-factor-auth/transaction',
      tuPlus: {
        toPlus: '/api/loyalty/balance',
        historicMovements: '/api/loyalty/transactions',
        configuration: '/api/loyalty/configuration',
        redemption: '/api/loyalty/redemption',
        otpGeneration: '/api/loyalty/otp/generate',
        closeToPlus: '/api/tu-plus-auth-ms/logout',
      },
      accountCertificate: '/api/certificates/account',
      registerAffiliationProducts: '/api/affiliation-products-v2/register',
      deleteAffiliationProducts: '/api/affiliation-products-v2/delete',
      pseTwoFa: '/api/pse/two-factor-auth/transaction',
      historicPayments: '/api/payments/historical',
      stocks: {
        all: '/api/stocks-aval',
        period: '/api/stocks-aval/periods',
        types: '/api/stocks-aval/types',
      },
      advance: {
        transfer: '/api/advances/execute-advance',
        twoFa: '/api/advances/two-factor-auth/transaction',
      },
      web_authn: {
        all: '/api/web-authn/credentials/all',
        auth: '/api/web-authn/authn',
        initAuth: '/api/web-authn/authn/init',
        initRegister: '/api/web-authn/register/init',
        register: '/api/web-authn/register',
        updateCredential: '/api/web-authn/credentials/update',
        deleteCredential: '/api/web-authn/credentials/delete',
      },
      transfers: {
        cost: '/api/transfers/cost',
        account_transfer: '/api/transfers/transfer',
        fast_transfer: '/api/transfers/fast-transfer',
      },
      valid_transaction: '/api/two-factor-auth/continue',
      activate_tc: '/api/product-administration/credit-card/activate',
      load_debit_cards: '/api/product-administration/debit-cards/search',
      code_auth: {
        allowed: '/api/admin-two-factor-auth/allowed-assign-enhanced-2fa',
        assign: '/api/admin-two-factor-auth/assign-enhanced-2fa',
        question:
          '/api/auth-manager/enrollment-secure-data/get-security-question',
        validate:
          '/api/auth-manager/enrollment-secure-data/validate-security-question',
        state: '/api/user-two-factor-auth/get',
      },
      order_of_payment: '/api/payroll-loans/all',
      tax_certificates: '/api/certificates/gfm',
      income_certificates: '/api/certificates/income-taxes',
      rental_certificates: '/api/certificates/income-taxes-credit-card',
      rac: '/api/certificates/rac',
      nicknames: {
        all: '/api/nicknames/all',
        create: '/api/nicknames/create',
        delete: '/api/nicknames/delete',
        update: '/api/nicknames/update',
      },
      pilaPayment: '/api/v2/payments/payment/pila',
      infoUser: '/api/auth-manager/secure-data/get',
      channel_lock: {
        create: '/api/administration-api/create-blocking-channels',
        update: '/api/administration-api/update-blocking-channels',
        get: '/api/administration-api/get-blocking-channels',
        delete: '/api/administration-api/delete-blocking-channels',
      },
      experian: '/api/experian/otp-evidente-master-flow',
      totp: {
        generate: '/api/totp/generate',
        devices: '/api/totp/devices',
        delete: '/api/totp/delete',
        register: '/api/totp/register',
        update: '/api/totp/update',
        validate: '/api/totp/validate',
      },
      unusualOperations: {
        query: '/api/unusual-operations-api/query-transactions',
        approve: '/api/unusual-operations-api/approve-reject-transactions',
      },
      limitManagement: {
        create: '/api/administration-limits-api/create-limits',
        get: '/api/administration-limits-api/get-limits',
        update: '/api/administration-limits-api/update-limits',
        delete: '/api/administration-limits-api/delete-limits',
      },
      otpAth: {
        generate: '/api/otp/enrollment',
        validate: '/api/otp/enrollment/validate',
      },
    },
  },
  languages: {
    es: 'es',
    es1: 'es1',
    en: 'en',
  },
  storeDev: [],
  resources: {
    base_assets: 'https://mi.bancopopular.com.co',
  },
  datadog_enable: false,
  datadog_clientToken: 'pubf3ee9fa9d61b4db31c6e0be6315e5cf0',
  datadog_appId: '1fd55354-9677-4356-b63a-7c6a7a9761d8',
  config_tealium: {
    account: 'adl',
    profile: 'popular',
    environment: 'prod',
  },
};
