export enum NavigateEnrollment {
  universalPassword = '/ClaveUnica',
  newUniversalPassword = '/NuevaClaveUniversal',
  validateUniversalPassword = '/ValidaClaveUniversal',
  validateCode = '/ValidaCodigo',
  loginSuccess = '/login-exitoso',
  validate = '/validate-',
  doNotExists = '/no-existe',
  limitExceedOnSecureDataGeneration = '/limite-superado-generacion-de-datos',
  limitExceedOnOtpGeneration = '/limite-superado-generacion-otp',
  serviceError = '/error-de-servicio',
  login = '/login',
  login_password_universal = '/login/clave-universal',
  login_error = '/login/error',
  key_debit = '/login/enrolamiento/validacion/clave-debito',
  data_insurance = '/login/enrolamiento/dato-seguro',
  new_password = '/login/enrolamiento/nueva-clave',
  conditions_use = '/login/enrolamiento/condiciones-uso',
  enter_insurance_data = '/login/enrolamiento/ingresar-dato-seguro',
  savings_account = '/login/enrolamiento/cuenta-ahorros',
  otp_buro = '/login/enrolamiento/otp-buro',
  otp_buro_error = '/login/enrolamiento/otp-buro/error',
  question_step1 = '/login/enrolamiento/otp-buro/pregunta/paso1',
  question_step2 = '/login/enrolamiento/otp-buro/pregunta/paso2',
  question_step3 = '/login/enrolamiento/otp-buro/pregunta/paso3',
  question_step4 = '/login/enrolamiento/otp-buro/pregunta/paso4',
}

export enum TitlesEnrollment {
  universalPassword = 'Clave unica',
  newUniversalPassword = 'Nueva clave universal',
  validateUniversalPassword = 'Valida clave universal',
  validateCode = 'Valida codigo',
  loginSuccess = 'login Exitoso',
  validate = 'Valida ',
  doNotExists = 'No existe',
  limitExceedOnSecureDataGeneration = 'limite superado en la generación de datos',
  limitExceedOnOtpGeneration = 'limite superado en la generación de otp',
  serviceError = 'error del servicio',
  login = 'login',
  login_password_universal = 'login clave universal',
  login_error = 'login error',
  key_debit = 'login enrolamiento validacion clave debito',
  data_insurance = 'login enrolamiento dato seguro',
  new_password = 'login enrolamiento nueva clave',
  conditions_use = 'login enrolamiento condiciones uso',
  enter_insurance_data = 'login enrolamiento ingresar dato seguro',
  savings_account = 'login enrolamiento cuenta ahorros',
  otp_buro = 'login enrolamiento otp buro',
  otp_buro_error = 'login enrolamiento otp buro error',
  question_step1 = 'login enrolamiento otp buro pregunta paso1',
  question_step2 = 'login enrolamiento otp buro pregunta paso2',
  question_step3 = 'login enrolamiento otp buro pregunta paso3',
  question_step4 = 'login enrolamiento otp buro pregunta paso4',
}
