export enum CARD_TYPES_CLASS {
  VISA_CLASSIC = 'visa_classic',
  VISA_GOLD = 'visa_gold',
  VISA_ENTERP = 'visa_enterp',
  VISA_BLACK = 'visa_black',
  VISA_POPULAR = 'visa_popular',
  VISA_PLATINIUM = 'visa_platinium',
  VISA_DIAMANT = 'visa_diamant',
  VISA_SIGNATURE = 'visa_signature',
  MC_REGULAR = 'mc_regular',
  MC_BLACK = 'mc_black',
  MC_GOLD = 'mc_gold',
  MC_PLATINO = 'mc_platino',
  BG_VISA = 'bg_visa',
  BG_MASTER = 'bg_master',
}

export enum CARD_TYPES_NAMES {
  VISA_CLASSIC = 'Clásica',
  VISA_GOLD = 'Gold',
  VISA_ENTERP = 'Entrprise',
  VISA_BLACK = 'Black',
  VISA_POPULAR = 'Regular',
  VISA_PLATINIUM = 'Platinium',
  VISA_DIAMANT = 'Diamant',
  VISA_SIGNATURE = 'Signature',
  MC_REGULAR = 'Regular',
  MC_BLACK = 'Black',
  MC_GOLD = 'Gold',
  MC_PLATINO = 'Platinium',
}
