import { TYPE_ACCOUNTS } from '@core/constants/types_account';

export const ORDER_PRODUCTS = [
  TYPE_ACCOUNTS.CURRENT_ACCOUNT,
  TYPE_ACCOUNTS.DEPOSIT_ACCOUNT,
  TYPE_ACCOUNTS.CERTIFIED_DEPOSIT_TERM,
  TYPE_ACCOUNTS.CREDIT_CARD,
  TYPE_ACCOUNTS.FREE_DESTINATION,
];
