export enum TYPE_ACCOUNTS {
  DEPOSIT_ACCOUNT = 'DEPOSIT_ACCOUNT',
  CREDIT_CARD = 'CREDIT_CARD',
  CURRENT_ACCOUNT = 'CURRENT_ACCOUNT',
  CERTIFIED_DEPOSIT_TERM = 'CERTIFIED_DEPOSIT_TERM',
  FIDUCIARY = 'FIDUCIARY',
  FREE_DESTINATION = 'FREE_DESTINATION',
  PAYROLLLOAN = 'PAYDAY_LOAN',
}
