export enum TYPE_STATUS_PRODUCTS {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  CANCELED_CREDIT = 'CANCELADO',
  ACTIVE_CREDIT = 'CREDITO ACTIVO',
}

export enum TYPE_STATUS_PRODUCTS_RESPONSE {
  ENABLED = 'Activo',
  DISABLED = 'Inactivo',
  OUTDATE = 'En mora',
  BLOCKED = 'Bloqueado',
  CANCELED = 'Cancelado',
  ACTIVE_CREDIT = 'Al día',
}
