export const MIN_AMOUNT_TRANSFER = 10000;
export const MAX_AMOUNT_TRANSFER = 5000000;

export const FAST_TRANSFER = 'FAST_TRANSFER';

export const MAX_LENGTH_DESCRIPTION = 80;
export const MAX_LENGTH_VOUCHER = 24;

export const MAX_LENGTH_DESTINATION_ACCOUNT_ID = 24;
export const MAX_LENGTH_CUSTOMER_ID = 24;
export const MAX_LENGTH_CUSTOMER_NAME = 80;
